default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  host: localhost
  username: test_guru_pg_user
  password: <%= ENV['TEST_GURU_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: test_guru_development

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  database: test_guru_production
